// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sefexhusypmjijgwpcdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlZmV4aHVzeXBtamlqZ3dwY2R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTc4MTAsImV4cCI6MjA3MTI3MzgxMH0.J29aCnEeWmzAxoB1PBqlxSKpUWyUVfDuftfsBECeUHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});